name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  validate:
    uses: mirenchaps/ci-platform/.github/workflows/terraform-validate.yml@main
    with:
      terraform-version: "1.9.8"
      roots: |
        environments/dev
        environments/stage
        environments/prod